- Grab/README.md
Added latest Grab pay questions for reference.
> Added latest Grab Pay Questions

- Uber/README.md
Uber Design Questions seen on Glassdoor
> Some design round questions from Glassdoor

- Amazon/README.md
This question I encountered when doing interview with Amazon Canada in 2017
> Add system design question

- Grab/README.md
> Question update

- Uber/README.md
This question was asked in the design round of Uber interview
> Added design question asked in uber onsite interview

- Google/README.md
- Microsoft/README.md
These questions are based on my recent experience of interview with Google.
> google telephonic quiz round questions

- Atlassian/README.md
Added some coding test questions for Atlassian!
> Added Atlassian !

- Grab/README.md
Added a coding question for Grab
> added a Grab coding question

- Adobe/README.md
- Intuit/README.md
Pull requests were directly merged into master branch, so this PR is to make both branches even.
> Added articles of Intuit and Adobe.

- Amazon/README.md
Added a coding and a system design question.
> Question added in Amazon

- Google/README.md
Added another problem. Requires dynamic programming and backtracking to solve. Taken from geeksforgeeks.
> Added another question.

- Amazon/README.md
- Added a coding question I was asked in Amazon
- Added a system design question I was asked in Amazon
> Amazon questions added

- BookMyShow/README.md
added a coding and OS question
> added for BookMyShow

- Uber/README.md
added 2 coding questions for Uber
> added for Uber

- AirAsia/README.md
I have added questions from the recent AirAsia placement drive at IIT-Dharwad.
> Added AirAsia Interview Questions

- Amazon/README.md
Added an Amazon interview question I was asked myself
> Added an Amazon question

- Adobe/README.md
- AirAsia/README.md
- Amazon/README.md
- BookMyShow/README.md
- Expedia/README.md
- Google/README.md
- Grab/README.md
- Intuit/README.md
- Microsoft/README.md
- MobiKwik/README.md
- NEC Technologies/README.md
- Ola Cabs/README.md
- Samsung/README.md
hey nice content. But there were some grammatical errors that I've corrected.
Please approve the pull request as hacktoberfest is ending.
Thank-you.
> Interview-Questions

- Flipkart/README.md
> Updated Flipkart.md

- LinkedIn/README.md
> New branch

- README.md
Optimized the company links that are present in the main Readme file.
Mainly 2 Benefits:
1. Reduce the file size
2. These links will work in any fork/any branch and for any person, even if some links are not merged in the main Repo.
Do let me know if anything else needs to be done. Will contribute the same
> Personalized links

- MakeMyTrip/README.md
Added MakeMyTrip Coding and Interview Questions.
> MMT Interview and Coding Questions

- Intel/README.md
(Contibutions towards hacktoberfest)
> Intel interview questions

- README.md
> #132 - Alphabetically categorize companies in README.md

- Roblox/README.md
I was asked this question in coding round for new grad sde role at Roblox.
> Roblox New Grad Questions

- Microsoft/README.md
Added questions in Microsoft article. #100
> Added Microsoft questions

- Google/README.md
Hi,
I have added the questions which I faced during my Google interview for the Site Reliability Engineer position. Please incorporate these changes.
Thanks,
Richa
> Google interview Questions Updated.

- Amazon/README.md
Added Amazon DSA and DBMS Technical Interview Round and Bar Raiser Round Questions
> Added Amazon DSA and DBMS Interview Round and Bar Raiser Round Questions

- Verizon/README.md
I am placed in this company and Uploaded the questions that were asked in Online Test and Technical Interview.
> Added Online test questions and interview questions for Verizon company

- Amazon/README.md
Add missing questions that I encountered during my interview with amazon.
> Add amazon interview questions

- Microsoft/README.md
Questions asked to me in Microsoft IDC internship interview have been added.
> Microsoft Internship Interview 2020 Questions added.

- Zomato/README.md
added dbms and coding round questions
> Added for zomato

- JP Morgan Chase/README.md
Added coding round questions for JPMC and also interview questions. 
Coding round conducted on : 06/09/20
Interview held on : 22/09/20
(BITS Pilani 2020 Internship Drive)
Location : JP Morgan Chase, Mumbai
> JPMC interview questions added

- Snowflake/README.md
- Twitter/README.md
Added recent twitter questions which I appeared to in Twitter's Early Career coding round for 2022 graduates on hackerrank.
> Twitter 2022 SWE Early Career coding round questions added

- Media.net/README.md
Added Media.net coding round questions which appeared for 2022 summer intern campus drive test.
> Added Media.net coding round questions

- Flipkart/README.md
I have added a question to the list which was recently asked to my friend. Hope this helps :)
> Updated Flipkart list

- Amazon/README.md
I have added a real Amazon internship interview question asked in 2021.
Please merge if you find my PR helpful 😊
> Added Amazon coding round question asked in internship interviews 2021
